import 'dotenv/config';
import express, { Request, Response, NextFunction } from 'express'; import cookieParser from 'cookie-parser'; import helmet from 'helmet'; import crypto from 'node:crypto'; import { z } from 'zod';
import { db, getSetting, migrate, setSetting } from './db.js'; import { encrypt, decrypt } from './crypto.js'; import { jellyfinLogin, jellyfinLoginAt, validateServer } from './jellyfin.js'; import { collectMetrics, collectPlayback } from './monitor.js';
const app = express(), PORT = Number(process.env.PORT || 3000), cookieName = 'jir_session';
app.use(helmet({ contentSecurityPolicy: false })); app.use(express.json({ limit: '100kb' })); app.use(cookieParser()); app.use(express.static('public'));
type Principal = { id: string; userId: string; username: string; isAdmin: boolean };
declare global { namespace Express { interface Request { principal?: Principal } } }
async function configured() { return Boolean(await getSetting('configured')); }
async function session(req: Request, res: Response, next: NextFunction) { const id = req.cookies[cookieName]; if (!id) return next(); const row = (await db.query('SELECT id,user_id,username,is_admin FROM sessions WHERE id=$1 AND expires_at > now()', [id])).rows[0]; if (row) req.principal = { id: row.id, userId: row.user_id, username: row.username, isAdmin: row.is_admin }; else res.clearCookie(cookieName); next(); }
app.use(session);
const requireAuth = (req: Request, res: Response, next: NextFunction) => req.principal ? next() : res.status(401).json({ error: 'Sign in required' });
const requireAdmin = (req: Request, res: Response, next: NextFunction) => req.principal?.isAdmin ? next() : res.status(403).json({ error: 'Administrator access required' });
function cookie(res: Response, id: string) { res.cookie(cookieName, id, { httpOnly: true, sameSite: 'strict', secure: process.env.SESSION_COOKIE_SECURE === 'true', maxAge: 1000 * 60 * 60 * 12 }); }
async function notify(issue: any) { const value = await getSetting('webhook_url'); if (!value) return; try { await fetch(decrypt(value), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: `New ${issue.issue_type} report from **${issue.username}**: ${issue.playback.itemName}\n${issue.description}` }) }); } catch { /* reporting must not fail if a webhook is down */ } }

app.get('/api/bootstrap', async (_req, res) => res.json({ configured: await configured(), serverName: await getSetting('server_name') || '' }));
app.post('/api/setup', async (req, res) => { if (await configured()) return res.status(409).json({ error: 'Setup is already complete' }); try { const body = z.object({ host: z.string().url(), apiKey: z.string().min(8), adminUsername: z.string().min(1).max(64), adminPassword: z.string().min(1).max(200) }).parse(req.body); const info = await validateServer(body.host, body.apiKey); const identity = await jellyfinLoginAt(body.host, body.adminUsername, body.adminPassword); await setSetting('jellyfin_host', body.host.replace(/\/$/, '')); await setSetting('jellyfin_api_key', encrypt(body.apiKey)); await setSetting('admin_user_id', identity.id); await setSetting('server_name', info.ServerName); await setSetting('configured', 'true'); const id = crypto.randomUUID(); await db.query('INSERT INTO sessions(id,user_id,username,is_admin,token,expires_at) VALUES($1,$2,$3,true,$4,now()+interval \'12 hours\')', [id, identity.id, identity.username, encrypt(identity.token)]); cookie(res, id); res.status(201).json({ ok: true }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Setup failed' }); } });
app.post('/api/auth/login', async (req, res) => { try { const body = z.object({ username: z.string().min(1), password: z.string().min(1) }).parse(req.body); const identity = await jellyfinLogin(body.username, body.password); const adminUserId = await getSetting('admin_user_id'); const migrationAdmin = !adminUserId && identity.serverAdmin; if (migrationAdmin) await setSetting('admin_user_id', identity.id); const id = crypto.randomUUID(), isAdmin = identity.id === adminUserId || migrationAdmin; await db.query('INSERT INTO sessions(id,user_id,username,is_admin,token,expires_at) VALUES($1,$2,$3,$4,$5,now()+interval \'12 hours\')', [id, identity.id, identity.username, isAdmin, encrypt(identity.token)]); cookie(res, id); res.json({ username: identity.username, isAdmin }); } catch (e) { res.status(401).json({ error: e instanceof Error ? e.message : 'Login failed' }); } });
app.post('/api/auth/logout', async (req, res) => { if (req.principal) await db.query('DELETE FROM sessions WHERE id=$1', [req.principal.id]); res.clearCookie(cookieName); res.status(204).end(); });
app.get('/api/me', requireAuth, (req, res) => res.json(req.principal));
app.get('/api/playback', requireAuth, async (req, res) => { const row = (await db.query("SELECT payload,last_seen FROM recent_playback WHERE user_id=$1 AND last_seen > now()-interval '5 minutes'", [req.principal!.userId])).rows[0]; res.json({ playback: row ? { ...row.payload, lastSeen: row.last_seen } : null }); });
app.post('/api/issues', requireAuth, async (req, res) => { try { const body = z.object({ issueType: z.enum(['playback', 'audio', 'video', 'subtitle', 'metadata', 'other']), description: z.string().trim().min(3).max(4000) }).parse(req.body); const p = (await db.query("SELECT payload,last_seen FROM recent_playback WHERE user_id=$1 AND last_seen > now()-interval '5 minutes'", [req.principal!.userId])).rows[0]; if (!p) throw new Error('No recent Jellyfin playback was found. Start playback, then try again.'); const metrics = (await db.query("SELECT captured_at,cpu_percent,memory_bytes,memory_limit,gpu_percent FROM metric_samples WHERE captured_at > now()-interval '5 minutes' ORDER BY captured_at", [])).rows; const row = (await db.query('INSERT INTO issues(issue_type,description,user_id,username,playback,metrics) VALUES($1,$2,$3,$4,$5,$6) RETURNING *', [body.issueType, body.description, req.principal!.userId, req.principal!.username, JSON.stringify({ ...p.payload, lastSeen: p.last_seen }), JSON.stringify(metrics)])).rows[0]; await notify(row); res.status(201).json({ id: row.id }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not create report' }); } });
app.get('/api/admin/dashboard', requireAdmin, async (_req, res) => { const [viewers, issues, metrics] = await Promise.all([db.query("SELECT username,payload,last_seen FROM recent_playback WHERE last_seen > now()-interval '5 minutes' ORDER BY last_seen DESC"), db.query('SELECT * FROM issues ORDER BY created_at DESC LIMIT 200'), db.query("SELECT captured_at,cpu_percent,memory_bytes,memory_limit,gpu_percent FROM metric_samples WHERE captured_at > now()-interval '24 hours' ORDER BY captured_at")]); res.json({ viewers: viewers.rows, issues: issues.rows, metrics: metrics.rows }); });
app.patch('/api/admin/issues/:id', requireAdmin, async (req, res) => { const status = z.enum(['open','resolved']).parse(req.body.status); await db.query('UPDATE issues SET status=$1 WHERE id=$2', [status, req.params.id]); res.status(204).end(); });
app.put('/api/admin/notifications', requireAdmin, async (req, res) => { const url = z.string().url().parse(req.body.webhookUrl); await setSetting('webhook_url', encrypt(url)); res.status(204).end(); });
app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => { console.error(err); res.status(500).json({ error: 'Unexpected server error' }); });
migrate().then(async () => { app.listen(PORT, () => console.log(`JellyPulse listening on :${PORT}`)); setInterval(collectPlayback, 30_000); setInterval(collectMetrics, 30_000); await collectPlayback(); await collectMetrics(); }).catch(e => { console.error('Database migration failed', e); process.exit(1); });
