import 'dotenv/config';
import express, { Request, Response, NextFunction } from 'express'; import cookieParser from 'cookie-parser'; import helmet from 'helmet'; import crypto from 'node:crypto'; import type { PoolClient } from 'pg'; import { z } from 'zod';
import { db, getSetting, migrate, setSetting } from './db.js'; import { encrypt, decrypt } from './crypto.js'; import { api, createJellyfinUser, jellyfinLogin, jellyfinLoginAt, playbackFromSession, validateServer } from './jellyfin.js'; import { collectMetrics, collectPlayback } from './monitor.js'; import { migrateLegacyDiscord, notificationConfigSchema, sendIssueNotifications, sendNotification } from './notifications.js';
const app = express(), PORT = Number(process.env.PORT || 3000), cookieName = 'jir_session';
app.use(helmet({ contentSecurityPolicy: false })); app.use(express.json({ limit: '100kb' })); app.use(cookieParser()); app.use(express.static('public'));
type Principal = { id: string; userId: string; username: string; isAdmin: boolean };
declare global { namespace Express { interface Request { principal?: Principal } } }
async function configured() { return Boolean(await getSetting('configured')); }
async function session(req: Request, res: Response, next: NextFunction) { const id = req.cookies[cookieName]; if (!id) return next(); const row = (await db.query('SELECT id,user_id,username,is_admin FROM sessions WHERE id=$1 AND expires_at > now()', [id])).rows[0]; if (row) req.principal = { id: row.id, userId: row.user_id, username: row.username, isAdmin: row.is_admin }; else res.clearCookie(cookieName); next(); }
app.use(session);
const requireAuth = (req: Request, res: Response, next: NextFunction) => req.principal ? next() : res.status(401).json({ error: 'Sign in required' });
const requireAdmin = (req: Request, res: Response, next: NextFunction) => req.principal?.isAdmin ? next() : res.status(403).json({ error: 'Administrator access required' });
function cookie(res: Response, id: string) { res.cookie(cookieName, id, { httpOnly: true, sameSite: 'strict', secure: process.env.SESSION_COOKIE_SECURE === 'true', maxAge: 1000 * 60 * 60 * 12 }); }
function tokenHash(token: string) { return crypto.createHash('sha256').update(token).digest('hex'); }
const notificationSecrets: Record<string, string[]> = { discord: ['webhookUrl'], slack: ['webhookUrl'], home_assistant: ['accessToken'], email: ['password'], ntfy: ['accessToken'], gotify: ['appToken'], telegram: ['botToken'], pushover: ['appToken','userKey'], webhook: ['webhookUrl'], apprise: ['urls'] };
function safeNotificationConfig(config: any) { const safe = { ...config }; for (const field of notificationSecrets[config.type] || []) delete safe[field]; return safe; }
async function playbackForUser(userId: string) { try { const sessions = await (await api('/Sessions?ActiveWithinSeconds=90')).json() as any[]; const current = sessions.filter(s => s.UserId === userId && s.NowPlayingItem).sort((a, b) => new Date(b.LastActivityDate || 0).getTime() - new Date(a.LastActivityDate || 0).getTime())[0]; if (current) return playbackFromSession(current); } catch (e) { console.warn('Live playback lookup failed; using the last observed item:', (e as Error).message); } const row = (await db.query('SELECT payload,last_seen FROM recent_playback WHERE user_id=$1', [userId])).rows[0]; return row ? { ...row.payload, lastSeen: row.last_seen, source: 'recent' as const } : null; }
async function activeViewers() { try { const sessions = await (await api('/Sessions?ActiveWithinSeconds=90')).json() as any[]; return sessions.filter(s => s.UserId && s.NowPlayingItem).map(s => ({ username: s.UserName || 'Unknown user', payload: playbackFromSession(s), last_seen: s.LastActivityDate || new Date().toISOString() })); } catch (e) { console.warn('Active viewer lookup failed:', (e as Error).message); return []; } }

app.get('/api/bootstrap', async (_req, res) => res.json({ configured: await configured(), serverName: await getSetting('server_name') || '' }));
app.post('/api/setup', async (req, res) => { if (await configured()) return res.status(409).json({ error: 'Setup is already complete' }); try { const body = z.object({ host: z.string().url(), apiKey: z.string().min(8), adminUsername: z.string().min(1).max(64), adminPassword: z.string().min(1).max(200) }).parse(req.body); const info = await validateServer(body.host, body.apiKey); const identity = await jellyfinLoginAt(body.host, body.adminUsername, body.adminPassword); await setSetting('jellyfin_host', body.host.replace(/\/$/, '')); await setSetting('jellyfin_api_key', encrypt(body.apiKey)); await setSetting('admin_user_id', identity.id); await setSetting('server_name', info.ServerName); await setSetting('configured', 'true'); res.clearCookie(cookieName); res.status(201).json({ ok: true, loginRequired: true }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Setup failed' }); } });
app.post('/api/auth/login', async (req, res) => { try { const body = z.object({ username: z.string().min(1), password: z.string().min(1) }).parse(req.body); const identity = await jellyfinLogin(body.username, body.password); const adminUserId = await getSetting('admin_user_id'); const migrationAdmin = !adminUserId && identity.serverAdmin; if (migrationAdmin) await setSetting('admin_user_id', identity.id); const id = crypto.randomUUID(), isAdmin = identity.id === adminUserId || migrationAdmin; await db.query('INSERT INTO sessions(id,user_id,username,is_admin,token,expires_at) VALUES($1,$2,$3,$4,$5,now()+interval \'12 hours\')', [id, identity.id, identity.username, isAdmin, encrypt(identity.token)]); cookie(res, id); res.json({ username: identity.username, isAdmin }); } catch (e) { res.status(401).json({ error: e instanceof Error ? e.message : 'Login failed' }); } });
app.post('/api/auth/link', async (req, res) => { try { const body = z.object({ token: z.string().regex(/^[A-Za-z0-9_-]{43}$/) }).parse(req.body); const row = (await db.query("SELECT id,user_id,username FROM access_links WHERE token_hash=$1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())", [tokenHash(body.token)])).rows[0]; if (!row) return res.status(401).json({ error: 'This access link is invalid, expired, or revoked' }); const user = await (await api(`/Users/${row.user_id}`)).json() as any; if (user.Policy?.IsDisabled || user.Policy?.EnableRemoteAccess === false) return res.status(401).json({ error: 'This Jellyfin user is no longer allowed to use private links' }); const id = crypto.randomUUID(); await db.query('INSERT INTO sessions(id,user_id,username,is_admin,token,expires_at) VALUES($1,$2,$3,false,$4,now()+interval \'12 hours\')', [id, row.user_id, user.Name, encrypt('access-link')]); await db.query('UPDATE access_links SET username=$1,last_used_at=now() WHERE id=$2', [user.Name, row.id]); cookie(res, id); res.json({ ok: true }); } catch { res.status(401).json({ error: 'This access link is invalid, expired, or revoked' }); } });
app.post('/api/auth/logout', async (req, res) => { if (req.principal) await db.query('DELETE FROM sessions WHERE id=$1', [req.principal.id]); res.clearCookie(cookieName); res.status(204).end(); });
app.post('/api/invites/inspect', async (req, res) => { try { const token = z.string().regex(/^[A-Za-z0-9_-]{43}$/).parse(req.body.token); const row = (await db.query('SELECT label,expires_at FROM user_invites WHERE token_hash=$1 AND expires_at>now()', [tokenHash(token)])).rows[0]; if (!row) return res.status(404).json({ error: 'This invitation is invalid, expired, or already used' }); res.json({ label: row.label, expiresAt: row.expires_at, serverName: await getSetting('server_name') || 'Jellyfin' }); } catch { res.status(404).json({ error: 'This invitation is invalid, expired, or already used' }); } });
app.post('/api/invites/redeem', async (req, res) => { let client: PoolClient | undefined; try { const body = z.object({ token: z.string().regex(/^[A-Za-z0-9_-]{43}$/), username: z.string().trim().min(1).max(64).refine(v => !/[\x00-\x1F\x7F]/.test(v), 'Username contains invalid characters'), password: z.string().min(8).max(200) }).parse(req.body); client = await db.connect(); await client.query('BEGIN'); const row = (await client.query('SELECT id FROM user_invites WHERE token_hash=$1 AND expires_at>now() FOR UPDATE', [tokenHash(body.token)])).rows[0]; if (!row) { await client.query('ROLLBACK'); return res.status(404).json({ error: 'This invitation is invalid, expired, or already used' }); } const user = await createJellyfinUser(body.username, body.password); await client.query('DELETE FROM user_invites WHERE id=$1', [row.id]); await client.query('COMMIT'); res.status(201).json({ username: user.Name }); } catch (e) { if (client) await client.query('ROLLBACK').catch(() => {}); res.status(400).json({ error: e instanceof Error ? e.message : 'Could not create Jellyfin account' }); } finally { client?.release(); } });
app.get('/api/me', requireAuth, (req, res) => res.json(req.principal));
app.get('/api/playback', requireAuth, async (req, res) => res.json({ playback: await playbackForUser(req.principal!.userId) }));
app.get('/api/reports', requireAuth, async (req, res) => { const reports = (await db.query('SELECT i.id,i.created_at,i.status,i.issue_type,i.issue_detail,i.description,i.playback,i.resolved_at,i.resolution_note,n.created_at AS popup_queued_at,n.delivered_at AS popup_delivered_at,n.last_error AS popup_error FROM issues i LEFT JOIN issue_resolution_notifications n ON n.issue_id=i.id WHERE i.user_id=$1 ORDER BY i.created_at DESC LIMIT 100', [req.principal!.userId])).rows; res.json({ reports }); });
const issueDetails: Record<string,string[]> = { playback: ['Playback stopped','Buffering','Will not start','Skipping or stuttering','App closed during playback'], audio: ['No audio','Audio out of sync','Wrong language','Distorted audio','Volume too quiet or loud'], video: ['Black screen','Glitching or artifacts','Wrong aspect ratio','Low video quality','Color or brightness issue'], subtitle: ['Missing subtitles','Wrong language','Wrong timing','Incorrect subtitle text','Subtitle styling or position'], metadata: ['Wrong title','Wrong artwork','Wrong episode order','Wrong description','Missing metadata'], other: ['Other issue'] };
app.post('/api/issues', requireAuth, async (req, res) => { try { const body = z.object({ issueType: z.enum(['playback', 'audio', 'video', 'subtitle', 'metadata', 'other']), issueDetail: z.string().trim().min(1).max(100), description: z.string().trim().max(4000).optional().default('') }).parse(req.body); if (!issueDetails[body.issueType].includes(body.issueDetail)) throw new Error('Choose a valid issue option'); const playback = await playbackForUser(req.principal!.userId); if (!playback) throw new Error('No current or previously observed Jellyfin playback was found. Start something in Jellyfin, then try again.'); if (playback.source === 'current') await db.query('INSERT INTO recent_playback(user_id,username,payload,last_seen) VALUES($1,$2,$3,now()) ON CONFLICT(user_id) DO UPDATE SET username=EXCLUDED.username,payload=EXCLUDED.payload,last_seen=now()', [req.principal!.userId, req.principal!.username, JSON.stringify(playback)]); const reportedPlayback = { ...playback, reportedAt: new Date().toISOString() }; const metrics = (await db.query("SELECT captured_at,cpu_percent,memory_bytes,memory_limit,gpu_percent FROM metric_samples WHERE captured_at > now()-interval '5 minutes' ORDER BY captured_at", [])).rows; const row = (await db.query('INSERT INTO issues(issue_type,issue_detail,description,user_id,username,playback,metrics) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *', [body.issueType, body.issueDetail, body.description, req.principal!.userId, req.principal!.username, JSON.stringify(reportedPlayback), JSON.stringify(metrics)])).rows[0]; void sendIssueNotifications(row).catch(e => console.warn('Notification dispatch failed:', e)); res.status(201).json({ id: row.id }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not create report' }); } });
app.get('/api/admin/dashboard', requireAdmin, async (_req, res) => { const [viewers, openReports, metrics] = await Promise.all([activeViewers(), db.query("SELECT count(*)::int AS count FROM issues WHERE status='open'"), db.query("SELECT captured_at,cpu_percent,memory_bytes,memory_limit,gpu_percent FROM metric_samples WHERE captured_at > now()-interval '24 hours' ORDER BY captured_at")]); res.json({ viewers, openReports: openReports.rows[0].count, metrics: metrics.rows }); });
app.get('/api/admin/reports', requireAdmin, async (_req, res) => { const reports = (await db.query('SELECT i.*,n.created_at AS notification_queued_at,n.delivered_at AS popup_delivered_at,n.last_attempt_at AS popup_last_attempt_at,n.last_error AS popup_error FROM issues i LEFT JOIN issue_resolution_notifications n ON n.issue_id=i.id ORDER BY i.created_at DESC LIMIT 500')).rows; res.json({ reports }); });
app.get('/api/admin/users', requireAdmin, async (_req, res) => { try { const jellyfinUsers = await (await api('/Users')).json() as any[]; const [historyResult, recentResult, reportResult] = await Promise.all([db.query("SELECT user_id,username,payload,started_at,last_seen,observed_seconds FROM watch_history ORDER BY last_seen DESC LIMIT 5000"), db.query('SELECT user_id,payload,last_seen FROM recent_playback'), db.query('SELECT user_id,count(*)::int AS total,count(*) FILTER (WHERE status=\'open\')::int AS open FROM issues GROUP BY user_id')]); const histories = historyResult.rows, recent = new Map(recentResult.rows.map(r => [r.user_id, r])), reports = new Map(reportResult.rows.map(r => [r.user_id, r])); const users = jellyfinUsers.map(user => { const watched = histories.filter(h => h.user_id === user.Id), totals = new Map<string,{ label:string; seconds:number }>(); for (const h of watched) { const label = h.payload?.seriesName || h.payload?.itemName || 'Unknown item', key = String(label).toLowerCase(), value = totals.get(key) || { label, seconds: 0 }; value.seconds += Number(h.observed_seconds) || 0; totals.set(key, value); } const favorite = [...totals.values()].sort((a,b) => b.seconds-a.seconds)[0]; const latest = recent.get(user.Id) as any, report = reports.get(user.Id) as any; return { id: user.Id, username: user.Name, disabled: Boolean(user.Policy?.IsDisabled), isAdministrator: Boolean(user.Policy?.IsAdministrator), lastLogin: user.LastLoginDate || null, lastActivity: user.LastActivityDate || null, recent: latest ? { ...latest.payload, lastSeen: latest.last_seen } : null, favorite: favorite?.label || null, observedSeconds: watched.reduce((sum,h) => sum+(Number(h.observed_seconds)||0),0), watchEntries: watched.length, reports: Number(report?.total)||0, openReports: Number(report?.open)||0 }; }); res.json({ users }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not load Jellyfin users' }); } });
app.get('/api/admin/watch-history', requireAdmin, async (req, res) => { try { const userId = z.string().optional().parse(req.query.userId); const result = userId ? await db.query('SELECT id,user_id,username,payload,started_at,last_seen,observed_seconds FROM watch_history WHERE user_id=$1 ORDER BY last_seen DESC LIMIT 500', [userId]) : await db.query('SELECT id,user_id,username,payload,started_at,last_seen,observed_seconds FROM watch_history ORDER BY last_seen DESC LIMIT 500'); res.json({ history: result.rows }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not load watch history' }); } });
app.get('/api/admin/settings', requireAdmin, async (_req, res) => res.json({ host: await getSetting('jellyfin_host') || '', serverName: await getSetting('server_name') || '', apiKeyConfigured: Boolean(await getSetting('jellyfin_api_key')) }));
app.put('/api/admin/settings/jellyfin', requireAdmin, async (req, res) => { try { const body = z.object({ host: z.string().url(), apiKey: z.string().optional().default(''), adminPassword: z.string().min(1).max(200) }).parse(req.body), host = body.host.replace(/\/$/, ''), encryptedKey = await getSetting('jellyfin_api_key'), key = body.apiKey.trim() || (encryptedKey ? decrypt(encryptedKey) : ''); if (!key) throw new Error('Enter a Jellyfin API key'); const info = await validateServer(host, key), identity = await jellyfinLoginAt(host, req.principal!.username, body.adminPassword); await setSetting('jellyfin_host', host); await setSetting('jellyfin_api_key', encrypt(key)); await setSetting('admin_user_id', identity.id); await setSetting('server_name', info.ServerName); await db.query('UPDATE sessions SET user_id=$1 WHERE id=$2', [identity.id, req.principal!.id]); res.json({ ok: true, serverName: info.ServerName }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not update Jellyfin configuration' }); } });
app.patch('/api/admin/issues/:id', requireAdmin, async (req, res) => { let client: PoolClient | undefined; try { const body = z.object({ status: z.enum(['open','resolved']), resolutionNote: z.string().trim().max(2000).optional().default('') }).parse(req.body); client = await db.connect(); await client.query('BEGIN'); const issue = (await client.query('SELECT id,user_id FROM issues WHERE id=$1 FOR UPDATE', [req.params.id])).rows[0]; if (!issue) { await client.query('ROLLBACK'); return res.status(404).json({ error: 'Report not found' }); } if (body.status === 'resolved') { const note = body.resolutionNote || null; await client.query("UPDATE issues SET status='resolved',resolved_at=now(),resolution_note=$1 WHERE id=$2", [note, issue.id]); await client.query('INSERT INTO issue_resolution_notifications(issue_id,user_id) VALUES($1,$2) ON CONFLICT(issue_id) DO UPDATE SET user_id=EXCLUDED.user_id,created_at=now(),delivered_at=NULL,delivery_session_id=NULL,last_attempt_at=NULL,last_error=NULL', [issue.id, issue.user_id]); } else { await client.query("UPDATE issues SET status='open',resolved_at=NULL,resolution_note=NULL WHERE id=$1", [issue.id]); await client.query('DELETE FROM issue_resolution_notifications WHERE issue_id=$1', [issue.id]); } await client.query('COMMIT'); res.json({ ok: true }); } catch (e) { if (client) await client.query('ROLLBACK').catch(() => {}); res.status(400).json({ error: e instanceof Error ? e.message : 'Could not update report' }); } finally { client?.release(); } });
app.put('/api/admin/notifications', requireAdmin, async (req, res) => { const url = z.string().url().parse(req.body.webhookUrl); await setSetting('webhook_url', encrypt(url)); res.status(204).end(); });
app.get('/api/admin/notifications', requireAdmin, async (_req, res) => { const rows = (await db.query('SELECT id,type,label,enabled,created_at,last_sent_at,last_error FROM notification_destinations ORDER BY created_at')).rows; res.json({ destinations: rows }); });
app.get('/api/admin/notifications/:id', requireAdmin, async (req, res) => { try { const row = (await db.query('SELECT id,type,label,enabled,config FROM notification_destinations WHERE id=$1', [req.params.id])).rows[0]; if (!row) return res.status(404).json({ error: 'Notification destination not found' }); const config = notificationConfigSchema.parse(JSON.parse(decrypt(row.config))); res.json({ id: row.id, type: row.type, label: row.label, enabled: row.enabled, config: safeNotificationConfig(config), secretFields: notificationSecrets[row.type] || [] }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not load notification destination' }); } });
app.post('/api/admin/notifications', requireAdmin, async (req, res) => { try { const label = z.string().trim().min(1).max(80).parse(req.body.label), config = notificationConfigSchema.parse(req.body.config), id = crypto.randomUUID(); await db.query('INSERT INTO notification_destinations(id,type,label,config) VALUES($1,$2,$3,$4)', [id, config.type, label, encrypt(JSON.stringify(config))]); res.status(201).json({ id }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not add notification destination' }); } });
app.put('/api/admin/notifications/:id', requireAdmin, async (req, res) => { try { const row = (await db.query('SELECT type,config FROM notification_destinations WHERE id=$1', [req.params.id])).rows[0]; if (!row) return res.status(404).json({ error: 'Notification destination not found' }); const label = z.string().trim().min(1).max(80).parse(req.body.label), existing = notificationConfigSchema.parse(JSON.parse(decrypt(row.config))), incoming = z.record(z.unknown()).parse(req.body.config); if (incoming.type !== existing.type) return res.status(400).json({ error: 'Provider type cannot be changed; create a new destination instead' }); const merged: any = { ...existing }; for (const [key,value] of Object.entries(incoming)) if (value !== '' && value !== null && value !== undefined) merged[key] = value; const config = notificationConfigSchema.parse(merged); await db.query('UPDATE notification_destinations SET label=$1,config=$2,type=$3,last_error=NULL WHERE id=$4', [label, encrypt(JSON.stringify(config)), config.type, req.params.id]); res.status(204).end(); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not update notification destination' }); } });
app.patch('/api/admin/notifications/:id', requireAdmin, async (req, res) => { const enabled = z.boolean().parse(req.body.enabled); await db.query('UPDATE notification_destinations SET enabled=$1 WHERE id=$2', [enabled, req.params.id]); res.status(204).end(); });
app.delete('/api/admin/notifications/:id', requireAdmin, async (req, res) => { await db.query('DELETE FROM notification_destinations WHERE id=$1', [req.params.id]); res.status(204).end(); });
app.post('/api/admin/notifications/:id/test', requireAdmin, async (req, res) => { try { const row = (await db.query('SELECT config FROM notification_destinations WHERE id=$1', [req.params.id])).rows[0]; if (!row) return res.status(404).json({ error: 'Notification destination not found' }); const config = notificationConfigSchema.parse(JSON.parse(decrypt(row.config))); await sendNotification(config, { issue_type: 'test', username: req.principal!.username, description: 'Your JellyPulse notification destination is working.', playback: { itemName: 'Test notification' } }); await db.query('UPDATE notification_destinations SET last_sent_at=now(),last_error=NULL WHERE id=$1', [req.params.id]); res.json({ ok: true }); } catch (e) { const message = e instanceof Error ? e.message : 'Test failed'; await db.query('UPDATE notification_destinations SET last_error=$1 WHERE id=$2', [message.slice(0, 500), req.params.id]); res.status(400).json({ error: message }); } });
app.get('/api/admin/access-links', requireAdmin, async (_req, res) => { const users = await (await api('/Users')).json() as any[]; const links = (await db.query('SELECT id,user_id,username,label,created_at,expires_at,revoked_at,last_used_at FROM access_links ORDER BY created_at DESC')).rows; res.json({ users: users.filter(u => !u.Policy?.IsDisabled && u.Policy?.EnableRemoteAccess !== false).map(u => ({ id: u.Id, username: u.Name })), links }); });
app.post('/api/admin/access-links', requireAdmin, async (req, res) => { try { const body = z.object({ userId: z.string().min(1), label: z.string().trim().min(1).max(80), expiresDays: z.union([z.literal(0), z.number().int().min(1).max(3650)]) }).parse(req.body); const users = await (await api('/Users')).json() as any[], user = users.find(u => u.Id === body.userId); if (!user) return res.status(404).json({ error: 'Jellyfin user not found' }); if (user.Policy?.IsDisabled || user.Policy?.EnableRemoteAccess === false) return res.status(400).json({ error: 'That Jellyfin user is disabled or cannot access JellyPulse remotely' }); const token = crypto.randomBytes(32).toString('base64url'), id = crypto.randomUUID(), expiresAt = body.expiresDays === 0 ? null : new Date(Date.now() + body.expiresDays * 86_400_000); await db.query('INSERT INTO access_links(id,user_id,username,label,token_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6)', [id, user.Id, user.Name, body.label, tokenHash(token), expiresAt]); res.status(201).json({ id, path: `/#/access/${token}` }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not create access link' }); } });
app.delete('/api/admin/access-links/:id', requireAdmin, async (req, res) => { await db.query('UPDATE access_links SET revoked_at=now() WHERE id=$1', [req.params.id]); res.status(204).end(); });
app.get('/api/admin/user-invites', requireAdmin, async (_req, res) => { await db.query('DELETE FROM user_invites WHERE expires_at<=now()'); const invites = (await db.query('SELECT id,label,created_at,expires_at FROM user_invites ORDER BY created_at DESC')).rows; res.json({ invites }); });
app.post('/api/admin/user-invites', requireAdmin, async (req, res) => { try { const body = z.object({ label: z.string().trim().min(1).max(80), durationMinutes: z.union([z.literal(30),z.literal(60),z.literal(1440),z.literal(10080)]) }).parse(req.body); const token = crypto.randomBytes(32).toString('base64url'), id = crypto.randomUUID(), expiresAt = new Date(Date.now() + body.durationMinutes * 60_000); await db.query('INSERT INTO user_invites(id,label,token_hash,expires_at) VALUES($1,$2,$3,$4)', [id, body.label, tokenHash(token), expiresAt]); res.status(201).json({ id, path: `/#/join/${token}`, expiresAt }); } catch (e) { res.status(400).json({ error: e instanceof Error ? e.message : 'Could not create user invitation' }); } });
app.delete('/api/admin/user-invites/:id', requireAdmin, async (req, res) => { await db.query('DELETE FROM user_invites WHERE id=$1', [req.params.id]); res.status(204).end(); });
app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => { console.error(err); res.status(500).json({ error: 'Unexpected server error' }); });
migrate().then(async () => { try { await migrateLegacyDiscord(await getSetting('webhook_url')); } catch (e) { console.warn('Legacy Discord migration skipped:', e); } app.listen(PORT, () => console.log(`JellyPulse listening on :${PORT}`)); setInterval(collectPlayback, 30_000); setInterval(collectMetrics, 30_000); await collectPlayback(); await collectMetrics(); }).catch(e => { console.error('Database migration failed', e); process.exit(1); });
